# #deployment yaml
# apiVersion: apps/v1 # version of the kubernetes api being used
# kind: Deployment 

# metadata: # provides information about the kubernetes resources you are creating
#   name: react-app # name of the deployment
#   namespace: react-demo # tells kubernetes in which namespace the deployment will be placed

# spec: # defines how your application should run
#   replicas: 3 # tells kubernetes to run 3 identical pods of this app

#   selector: # tells the Deployment which pods it manages based on labels
#     matchLabels:
#       app: react-app # in this case it manages all pods wiht the label app: react-app

#   template: # this defines the template for creating pods managed by the deployment
#     metadata:
#       labels:
#         app: react-app # these labels are added to the pod, and must match the selector above. this links the Deployment to its pods

#     spec: # this section defines the containers inside each pod
#       containers:
#         - name: react-app-container # this is the name of the container inside the pod
#           image: react-kube-demo # the docker image to be used
#           imagePullPolicy: Never
#           ports:
#             - containerPort: 80 # the port used to expose our application