apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: react-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80