apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: react-demo
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}